services:
  # File Sync Server
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: filesync-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/filesync
      - SPRING_DATASOURCE_USERNAME=filesync
      - SPRING_DATASOURCE_PASSWORD=filesync123
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    volumes:
      - ./server/storage:/app/storage
      - ./server/logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - filesync-network

  # File Sync Client 1 (Device 1)
  client1:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: filesync-client1
    ports:
      - "8081:8081"
    environment:
      - SERVER_URL=http://server:8080/api
      - CLIENT_ID=device-1
      - DISPLAY=host.docker.internal:0
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - ./client/sync:/app/sync
      - ./client/client.properties:/app/client.properties
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - filesync-network

  # File Sync Client 2 (Device 2) 
  client2:
    build:
      context: .
      dockerfile: client2/Dockerfile
    container_name: filesync-client2
    ports:
      - "8082:8081"
    environment:
      - SERVER_URL=http://server:8080/api
      - CLIENT_ID=device-2
      - DISPLAY=host.docker.internal:0
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - ./client2/sync:/app/sync
      - ./client2/client.properties:/app/client.properties
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - filesync-network

  postgres:
    image: postgres:15-alpine
    container_name: filesync-postgres
    environment:
      POSTGRES_DB: filesync
      POSTGRES_USER: filesync
      POSTGRES_PASSWORD: filesync123
      PGUSER: filesync
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U filesync -d filesync"]
      interval: 30s
      timeout: 10s
    networks:
      - filesync-network

  redis:
    image: redis:7-alpine
    container_name: filesync-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - filesync-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: filesync-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - filesync-network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  filesync-network:
    driver: bridge
