spring:
  application:
    name: file-sync-server
  
  profiles:
    active: dev
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/filesync}
    username: ${SPRING_DATASOURCE_USERNAME:filesync}
    password: ${SPRING_DATASOURCE_PASSWORD:filesync123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    virtual-host: /
  
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey1234567890123456789012345678901234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ123456789012345134FGSDFGSDF234ASAGSGFDSDFGGGSDG34534534TERFGSDFG234523456SDFGHWTYHKJFJK456345}
      expiration: 86400000 # 24 hours
      refresh-expiration: 604800000 # 7 days

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: true
    defaults:
      enabled: true

logging:
  level:
    com.filesync: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

filesync:
  storage:
    base-path: ./storage
    max-file-size: 104857600 # 100MB
    chunk-size: 5242880 # 5MB
  security:
    cors:
      allowed-origins: "http://localhost:3000,http://localhost:8081"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
